[package]
name = "udpproxi"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = "1"
tokio = { version = "1", default-features = false, features = ["rt", "time", "macros"] }
chrono = "0.4"
log = "0.4"
